### ISSUE TITLE
As an API consumer I want to have more Beacon status information visible without authentication

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/beacon-suedtirol-api#39]
In the next version of the API we will allow the users that uses the Open Data API (without authentication) to ask also for
- beacon’s status (the user wants to know if the beacon is working or not);
  -  online/ofline: the beacon is considered offline if there is an active issue or the battery status is low;
  -  planned/installed: the beacon that are in the database but not already installed has to be marked as planned;
-  `trusted_update_at`: last time that the information about the beacon status has been updated by a trusted user
- signal strength (txPower).

**Comment by davidebz** [comment]
* planned/installed: the beacon that are in the database but not already installed has to be marked as planned;
* last seen: last time that the information about the beacon status has been updated;
* signal strength (txPower)

To develop this part we need a test beacon and a kontakt.io account associated because this informations aren't stored in database: pending configuration, lastSeen and txPower

**Comment by davidebz** [comment]
per questa condizione:

planned/installed: the beacon that are in the database but not already installed has to be marked as planned;

verificare sulla mappa cosa viene usato per disegnare un icona grigia quando il beacon non è installato (blu pending configuration, verde ok)

**Comment by davidebz** [comment]
aggiornare la colonne trusted_update_at con current_timestamp ad ogni chiamata di trusted-beacon-controller
